// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

import {IAaveEcosystemReserveController} from './common/IAaveEcosystemReserveController.sol';
import {IStreamable} from './common/IStreamable.sol';
library MiscEthereum {
  // https://etherscan.io/address/0x2C7E6B153fC1AC0ae903f25BA023D4f2e7B3c38C
  IAaveEcosystemReserveController internal constant AAVE_ECOSYSTEM_RESERVE_CONTROLLER =
    IAaveEcosystemReserveController(0x2C7E6B153fC1AC0ae903f25BA023D4f2e7B3c38C);

  // https://etherscan.io/address/0x48CD3AEc07dAE812673b7b5f3d838B6cC201a03A
  address internal constant ECOSYSTEM_RESERVE = 0x48CD3AEc07dAE812673b7b5f3d838B6cC201a03A;

  // https://etherscan.io/address/0xb49f677943BC038e9857d61E7d053CaA2C1734C1
  address internal constant EUR_USD_AGGREGATOR = 0xb49f677943BC038e9857d61E7d053CaA2C1734C1;
}
