// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

import {IPoolAddressesProvider, IPool, IPoolConfigurator, IAaveOracle, IPoolDataProvider, IACLManager} from './ProtocolV3.sol';
import {ICollector} from './common/ICollector.sol';
library ProtocolV3Ethereum {
  // https://etherscan.io/address/0xF78064812cf5cb4F77aCdB3C887D9275d9c38d9d
  IPoolAddressesProvider internal constant POOL_ADDRESSES_PROVIDER =
    IPoolAddressesProvider(0xF78064812cf5cb4F77aCdB3C887D9275d9c38d9d);

  // https://etherscan.io/address/0xB858409691F6223D61281b68891883527f0832db
  IPool internal constant POOL = IPool(0xB858409691F6223D61281b68891883527f0832db);

  // https://etherscan.io/address/0x1cA0bcdD7b570ab415cC629494EeDd9B348E3457
  IPoolConfigurator internal constant POOL_CONFIGURATOR =
    IPoolConfigurator(0x1cA0bcdD7b570ab415cC629494EeDd9B348E3457);

  // https://etherscan.io/address/0x947cD1ED4d9B8650a03A686fFeF4722DaF08b13A
  IAaveOracle internal constant ORACLE = IAaveOracle(0x947cD1ED4d9B8650a03A686fFeF4722DaF08b13A);

  // https://etherscan.io/address/0x7A54566e657504304469699b3eFE1FD76DEa6Ae4
  address internal constant ACL_ADMIN = 0x7A54566e657504304469699b3eFE1FD76DEa6Ae4;

  // https://etherscan.io/address/0x18d3FB43Cd784A414aE68F0A9971eC2bbF20319f
  IACLManager internal constant ACL_MANAGER =
    IACLManager(0x18d3FB43Cd784A414aE68F0A9971eC2bbF20319f);

  // https://etherscan.io/address/0x2F6329d267cf7798BA295b2Fa49c48560AaDd2a8
  IPoolDataProvider internal constant AAVE_PROTOCOL_DATA_PROVIDER =
    IPoolDataProvider(0x2F6329d267cf7798BA295b2Fa49c48560AaDd2a8);

  // https://etherscan.io/address/0x43050Ff1e14De5D6f41067cFFDEb5674eCA6DCAA
  address internal constant POOL_IMPL = 0x43050Ff1e14De5D6f41067cFFDEb5674eCA6DCAA;

  // https://etherscan.io/address/0x87d937A57cc787AFa8A0632D98C0153C6B2d993e
  address internal constant POOL_CONFIGURATOR_IMPL = 0x87d937A57cc787AFa8A0632D98C0153C6B2d993e;

  // https://etherscan.io/address/0xAAFf1335499ffb3A707586D42b9E838482a95670
  address internal constant DEFAULT_INCENTIVES_CONTROLLER =
    0xAAFf1335499ffb3A707586D42b9E838482a95670;

  // https://etherscan.io/address/0x82AC1F18aDC1117a9C978e3230148dC5789b09a9
  address internal constant EMISSION_MANAGER = 0x82AC1F18aDC1117a9C978e3230148dC5789b09a9;

  // https://etherscan.io/address/0x48CD3AEc07dAE812673b7b5f3d838B6cC201a03A
  ICollector internal constant COLLECTOR = ICollector(0x48CD3AEc07dAE812673b7b5f3d838B6cC201a03A);

  // https://etherscan.io/address/0x05D5e1766e419Bc80a3F551C5EbB47EE80C9f3C2
  address internal constant DEFAULT_A_TOKEN_IMPL_REV_1 = 0x05D5e1766e419Bc80a3F551C5EbB47EE80C9f3C2;

  // https://etherscan.io/address/0xF0409E2f8d42AA642823Df02fcE8787F0Ea5De35
  address internal constant DEFAULT_VARIABLE_DEBT_TOKEN_IMPL_REV_1 =
    0xF0409E2f8d42AA642823Df02fcE8787F0Ea5De35;

  // https://etherscan.io/address/0x82dcCF206Ae2Ab46E2099e663F70DeE77caE7778
  address internal constant CAPS_PLUS_RISK_STEWARD = 0x82dcCF206Ae2Ab46E2099e663F70DeE77caE7778;

  // https://etherscan.io/address/0x7C7143f4bE189928A6a98D8686c5e84c893c59c7
  address internal constant RISK_STEWARD = 0x7C7143f4bE189928A6a98D8686c5e84c893c59c7;

  // https://etherscan.io/address/0x2eE68ACb6A1319de1b49DC139894644E424fefD6
  address internal constant FREEZING_STEWARD = 0x2eE68ACb6A1319de1b49DC139894644E424fefD6;

  // https://etherscan.io/address/0x1728B83a862c99aFf02DD412b3058C2028E69c03
  address internal constant DEBT_SWAP_ADAPTER = 0x1728B83a862c99aFf02DD412b3058C2028E69c03;

  // https://etherscan.io/address/0x616f6E1cB7620860973051FeF7000c22154cb8fa
  address internal constant CONFIG_ENGINE = 0x616f6E1cB7620860973051FeF7000c22154cb8fa;

  // https://etherscan.io/address/0xBb1527b03AE4C90960169855081c5973497c360C
  address internal constant POOL_ADDRESSES_PROVIDER_REGISTRY =
    0xBb1527b03AE4C90960169855081c5973497c360C;

  // https://etherscan.io/address/0xB90c2D7fA877FAdb125922dE8EEa255220E9b075
  address internal constant STATIC_A_TOKEN_FACTORY = 0xB90c2D7fA877FAdb125922dE8EEa255220E9b075;

  // https://etherscan.io/address/0x1728B83a862c99aFf02DD412b3058C2028E69c03
  address internal constant REPAY_WITH_COLLATERAL_ADAPTER =
    0x1728B83a862c99aFf02DD412b3058C2028E69c03;

  // https://etherscan.io/address/0x806DCe7290f12e69628C693eBcaFAba0E7B99eE9
  address internal constant SWAP_COLLATERAL_ADAPTER = 0x806DCe7290f12e69628C693eBcaFAba0E7B99eE9;

  // https://etherscan.io/address/0xC60e4898F744411b1Cc87167190DA492e383a35a
  address internal constant UI_INCENTIVE_DATA_PROVIDER = 0xC60e4898F744411b1Cc87167190DA492e383a35a;

  // https://etherscan.io/address/0xE3365D6f330F8465A768aABEe4c2863265D1D862
  address internal constant UI_POOL_DATA_PROVIDER = 0xE3365D6f330F8465A768aABEe4c2863265D1D862;

  // https://etherscan.io/address/0xBE40EBB3d2F424443A3D299466f014e62aDfc58F
  address internal constant WALLET_BALANCE_PROVIDER = 0xBE40EBB3d2F424443A3D299466f014e62aDfc58F;

  // https://etherscan.io/address/0xFE4A6bc973071e057273De208897119EC50d18Ca
  address internal constant WETH_GATEWAY = 0xFE4A6bc973071e057273De208897119EC50d18Ca;

  // https://etherscan.io/address/0xE11791f536F02458877EE9A32893e26708A87Ed6
  address internal constant WITHDRAW_SWAP_ADAPTER = 0xE11791f536F02458877EE9A32893e26708A87Ed6;

  // https://etherscan.io/address/0x9Cfb5013f812F86747cA6e293017dFA63cC5b761
  address internal constant DELEGATION_AWARE_A_TOKEN_IMPL_REV_1 =
    0x9Cfb5013f812F86747cA6e293017dFA63cC5b761;
}
library ProtocolV3EthereumAssets {
  // https://etherscan.io/address/0x6B175474E89094C44Da98b954EedeAC495271d0F
  address internal constant DAI_UNDERLYING = 0x6B175474E89094C44Da98b954EedeAC495271d0F;

  uint8 internal constant DAI_DECIMALS = 18;

  // https://etherscan.io/address/0xA31a5C3739C8ef1B2eEec5240B1F2b83AdEd8D3B
  address internal constant DAI_A_TOKEN = 0xA31a5C3739C8ef1B2eEec5240B1F2b83AdEd8D3B;

  // https://etherscan.io/address/0xfADb8693c7e138feD8DE4e31029862a026858A6C
  address internal constant DAI_V_TOKEN = 0xfADb8693c7e138feD8DE4e31029862a026858A6C;

  // https://etherscan.io/address/0xAed0c38402a5d19df6E4c03F4E2DceD6e29c1ee9
  address internal constant DAI_ORACLE = 0xAed0c38402a5d19df6E4c03F4E2DceD6e29c1ee9;

  // https://etherscan.io/address/0x27534ECe0dbE9a7b7B97067aD023029b71B2D9eC
  address internal constant DAI_INTEREST_RATE_STRATEGY = 0x27534ECe0dbE9a7b7B97067aD023029b71B2D9eC;

  // https://etherscan.io/address/0x4972cD62882E837dB885367311cC75A62F47fdfF
  address internal constant DAI_STATIC_A_TOKEN = 0x4972cD62882E837dB885367311cC75A62F47fdfF;

  // https://etherscan.io/address/0x514910771AF9Ca656af840dff83E8264EcF986CA
  address internal constant LINK_UNDERLYING = 0x514910771AF9Ca656af840dff83E8264EcF986CA;

  uint8 internal constant LINK_DECIMALS = 18;

  // https://etherscan.io/address/0x5e2A65Ac70B5D38C53Cb40aB5494dD4920CeEc17
  address internal constant LINK_A_TOKEN = 0x5e2A65Ac70B5D38C53Cb40aB5494dD4920CeEc17;

  // https://etherscan.io/address/0x2B5d6442B7145e44097fca48200a4eFE770929E6
  address internal constant LINK_V_TOKEN = 0x2B5d6442B7145e44097fca48200a4eFE770929E6;

  // https://etherscan.io/address/0x2c1d072e956AFFC0D435Cb7AC38EF18d24d9127c
  address internal constant LINK_ORACLE = 0x2c1d072e956AFFC0D435Cb7AC38EF18d24d9127c;

  // https://etherscan.io/address/0x58c7888C61Cf8d12E9eE51eFdf9EddBF101bdFa2
  address internal constant LINK_INTEREST_RATE_STRATEGY =
    0x58c7888C61Cf8d12E9eE51eFdf9EddBF101bdFa2;

  // https://etherscan.io/address/0xaCD5D8e1897EE284AB0710f9bB693476b59d95F0
  address internal constant LINK_STATIC_A_TOKEN = 0xaCD5D8e1897EE284AB0710f9bB693476b59d95F0;

  // https://etherscan.io/address/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48
  address internal constant USDC_UNDERLYING = 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48;

  uint8 internal constant USDC_DECIMALS = 6;

  // https://etherscan.io/address/0xef281E47Ee59dE62Df36AE535DA54dE54ea316CC
  address internal constant USDC_A_TOKEN = 0xef281E47Ee59dE62Df36AE535DA54dE54ea316CC;

  // https://etherscan.io/address/0xFe6f3B7107e517156B84833c9C2703900808bF8a
  address internal constant USDC_V_TOKEN = 0xFe6f3B7107e517156B84833c9C2703900808bF8a;

  // https://etherscan.io/address/0x8fFfFfd4AfB6115b954Bd326cbe7B4BA576818f6
  address internal constant USDC_ORACLE = 0x8fFfFfd4AfB6115b954Bd326cbe7B4BA576818f6;

  // https://etherscan.io/address/0x58c7888C61Cf8d12E9eE51eFdf9EddBF101bdFa2
  address internal constant USDC_INTEREST_RATE_STRATEGY =
    0x58c7888C61Cf8d12E9eE51eFdf9EddBF101bdFa2;

  // https://etherscan.io/address/0x15896439Ad225b9800328cDD8592638355FD5067
  address internal constant USDC_STATIC_A_TOKEN = 0x15896439Ad225b9800328cDD8592638355FD5067;

  // https://etherscan.io/address/0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599
  address internal constant WBTC_UNDERLYING = 0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599;

  uint8 internal constant WBTC_DECIMALS = 8;

  // https://etherscan.io/address/0x26a885cA661Fb364C76457C18B257888C7564ADA
  address internal constant WBTC_A_TOKEN = 0x26a885cA661Fb364C76457C18B257888C7564ADA;

  // https://etherscan.io/address/0x049ac7f92867b0b7973e705a7e264BC17e0e5333
  address internal constant WBTC_V_TOKEN = 0x049ac7f92867b0b7973e705a7e264BC17e0e5333;

  // https://etherscan.io/address/0xF4030086522a5bEEa4988F8cA5B36dbC97BeE88c
  address internal constant WBTC_ORACLE = 0xF4030086522a5bEEa4988F8cA5B36dbC97BeE88c;

  // https://etherscan.io/address/0x58c7888C61Cf8d12E9eE51eFdf9EddBF101bdFa2
  address internal constant WBTC_INTEREST_RATE_STRATEGY =
    0x58c7888C61Cf8d12E9eE51eFdf9EddBF101bdFa2;

  // https://etherscan.io/address/0x19802f5CcF85545454E094601fAd4F8FA0B1F9d3
  address internal constant WBTC_STATIC_A_TOKEN = 0x19802f5CcF85545454E094601fAd4F8FA0B1F9d3;

  // https://etherscan.io/address/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
  address internal constant WETH_UNDERLYING = 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2;

  uint8 internal constant WETH_DECIMALS = 18;

  // https://etherscan.io/address/0x140F9fE366734855C3cEE1cf8BC0b18faf8Cc807
  address internal constant WETH_A_TOKEN = 0x140F9fE366734855C3cEE1cf8BC0b18faf8Cc807;

  // https://etherscan.io/address/0xAd408C45D18efae040692D7FDB129381A8A3ebe6
  address internal constant WETH_V_TOKEN = 0xAd408C45D18efae040692D7FDB129381A8A3ebe6;

  // https://etherscan.io/address/0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419
  address internal constant WETH_ORACLE = 0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419;

  // https://etherscan.io/address/0x58c7888C61Cf8d12E9eE51eFdf9EddBF101bdFa2
  address internal constant WETH_INTEREST_RATE_STRATEGY =
    0x58c7888C61Cf8d12E9eE51eFdf9EddBF101bdFa2;

  // https://etherscan.io/address/0x622D44F60d85F36bf535958dee871AF76388BC7B
  address internal constant WETH_STATIC_A_TOKEN = 0x622D44F60d85F36bf535958dee871AF76388BC7B;

  // https://etherscan.io/address/0xdAC17F958D2ee523a2206206994597C13D831ec7
  address internal constant USDT_UNDERLYING = 0xdAC17F958D2ee523a2206206994597C13D831ec7;

  uint8 internal constant USDT_DECIMALS = 6;

  // https://etherscan.io/address/0xcb5B804744283FA7b8060B5DcEaB2dDE106F43B9
  address internal constant USDT_A_TOKEN = 0xcb5B804744283FA7b8060B5DcEaB2dDE106F43B9;

  // https://etherscan.io/address/0x0D49C70FcB235B771EafC54BC51b41cD040d47e8
  address internal constant USDT_V_TOKEN = 0x0D49C70FcB235B771EafC54BC51b41cD040d47e8;

  // https://etherscan.io/address/0x3E7d1eAB13ad0104d2750B8863b489D65364e32D
  address internal constant USDT_ORACLE = 0x3E7d1eAB13ad0104d2750B8863b489D65364e32D;

  // https://etherscan.io/address/0x58c7888C61Cf8d12E9eE51eFdf9EddBF101bdFa2
  address internal constant USDT_INTEREST_RATE_STRATEGY =
    0x58c7888C61Cf8d12E9eE51eFdf9EddBF101bdFa2;

  // https://etherscan.io/address/0xc6CA48FDc1Cd2374688A800806f6A7D124929817
  address internal constant USDT_STATIC_A_TOKEN = 0xc6CA48FDc1Cd2374688A800806f6A7D124929817;

  // https://etherscan.io/address/0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9
  address internal constant AAVE_UNDERLYING = 0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9;

  uint8 internal constant AAVE_DECIMALS = 18;

  // https://etherscan.io/address/0x41e59497F07B58eBc61F78bEb4c93bb9b7Fe5BA2
  address internal constant AAVE_A_TOKEN = 0x41e59497F07B58eBc61F78bEb4c93bb9b7Fe5BA2;

  // https://etherscan.io/address/0xa7eB639043647124e6ac166473d59310Dd230dE5
  address internal constant AAVE_V_TOKEN = 0xa7eB639043647124e6ac166473d59310Dd230dE5;

  // https://etherscan.io/address/0x547a514d5e3769680Ce22B2361c10Ea13619e8a9
  address internal constant AAVE_ORACLE = 0x547a514d5e3769680Ce22B2361c10Ea13619e8a9;

  // https://etherscan.io/address/0x58c7888C61Cf8d12E9eE51eFdf9EddBF101bdFa2
  address internal constant AAVE_INTEREST_RATE_STRATEGY =
    0x58c7888C61Cf8d12E9eE51eFdf9EddBF101bdFa2;

  // https://etherscan.io/address/0xbBc7aEd919e3B26009a93850c9e8Ab10b4163879
  address internal constant AAVE_STATIC_A_TOKEN = 0xbBc7aEd919e3B26009a93850c9e8Ab10b4163879;
}
